# Mapping from COCO class names to custom Step 1 class labels
COCO_TO_STEP1 = {
    "car": "vehicle",
    "truck": "vehicle",
    "bus": "vehicle",
    "motorcycle": "vehicle",
    "bicycle": "vehicle",
    "person": "person",
    "traffic light": "traffic_light",
    "stop sign": "road_sign",
    "parking meter": "road_sign",
    "bench": "other",
    "fire hydrant": "road_sign",
    "trash can": "trash_can",
    "dog": "other",
    "cat": "other",
    "bird": "other",
    "potted plant": "other",
    "chair": "other",
    "sofa": "other",
    "tv": "other",
    "keyboard": "other",
    "backpack": "other",
    "umbrella": "other",
    "handbag": "other",
    "tie": "other",
    "suitcase": "other",
    "frisbee": "other",
    "skateboard": "other",
    "surfboard": "other",
    "bottle": "other",
    "cup": "other",
    "fork": "other",
    "knife": "other",
    "spoon": "other",
    "bowl": "other",
    "banana": "trash",
    "apple": "trash",
    "sandwich": "trash",
    "orange": "trash",
    "broccoli": "trash",
    "carrot": "trash",
    "hot dog": "trash",
    "pizza": "trash",
    "donut": "trash",
    "cake": "trash",
    "book": "other",
    "cell phone": "other",
    "laptop": "other",
    "mouse": "other",
    "remote": "other",
    "microwave": "other",
    "oven": "other",
    "toaster": "other",
    "sink": "other",
    "refrigerator": "other",
    "scissors": "other",
    "teddy bear": "other",
    "hair drier": "other",
    "toothbrush": "other"
}

def map_coco_label_to_step1(coco_label):
    return COCO_TO_STEP1.get(coco_label.lower(), "other")